package common;

public enum Status {
    OK,
    ERROR,
    ERROR_USER_ALREADY_EXIST,
    CONTROL_QUESTION,
    ANSWER_TO_CONTROL_QUESTION,
    REMIND_PASSWORD_OK,
    REMIND_PASSWORD_ERROR,
    FIND_BY_YEAR_REQUEST,
    FIND_BY_AUTHOR_REQUEST,
    FIND_BY_YEAR_RESPONSE,
    FIND_BY_AUTHOR_RESPONSE
}
